#########################################
#Códigos UNICODE para vocales con tilde #
#########################################
# á = \u00e1                 Á = \u00c1 #
# é = \u00e9                 É = \u00c9 #
# í = \u00ed                 Í = \u00cd #
# ó = \u00f3                 Ó = \u00d3 #
# ú = \u00fa                 Ú = \u00da #
#########################################

# Parámetros dinámicos de acceso a servicios
Server=http://localhost:8080
ServerServiciosLectura=http://localhost:8080
ServerEntidades=http://localhost:8080
ServerCtrlVerif=http://localhost:8080
UrlTerritorial=/terr/rest
UrlEspecies=/tax/rest
UrlEntidades=/rue/rest
UrlCtrlVerif=/ctrlVerif/rest

# Usuarios de acceso a API's REST:
# UsRestTax y UsRestTerr => sacvefor (para los servicios de taxonom\u00edas y territorial)
# UsRestRue => scvf-traz (para el RUE)
# UsRestCtrl => scvf-traz (para CTRL)
# UsRestCgl => scvf-traz (para CGL)
UsRestTax=sacvefor
UsRestTerr=sacvefor
UsRestRue=scvf-traz
UsRestCtrl=scvf-traz
UsRestCgl=scvf-traz
# Tiempo de vigencia del token recibido
TimeToken=3600000

# Claves para encriptar y desencriptar las contraseñas de los usurios
ClaveEncriptar=bosquesnativosycomunidad
ClaveDesencriptar=trazabilidad

# Estados Gu\u00edas
EstCerrada=CERRADA

# Tipos Gu\u00eda
TipoLocal=GESTION LOCAL
TipoPrimaira=PRIMARIA

# Tipos de Items
TipoItemGestLocal=GESTION LOCAL
TipoItemPrim=PRIMARIO
TipoItemDer=DERIVADO
TipoItemProd=PRODUCTIVO

# ------------------ #
# Datos Responsables #
# ------------------ #
EntidadBosques=Direcci\u00f3n de Bosques
EntidadBosqesSup_1=Direcci\u00f3n Nacional de Bosques, Ordenamiento Territorial y Suelos
EntidadBosqesSup_2=Subsecretar\u00eda de Planificaci\u00f3n y Ordenamiento Ambiental de Territorio
EntidadBosqesSup_3=Secretar\u00eda de Pol\u00edtica Ambiental, Cambio Clim\u00e1tico y Desarrollo Sustentable
EntidadBosqesSup_4=Ministerio de Ambiente y Desarrollo Sustentable
DomicilioBosques=Tucum\u00e1n 633 6° Piso - CABA
TelBosques=(54) (11) 5218-4640
emailBosques=rincostante@ambiente.gob.ar

# -------------------------------------------------- #
# Tipos de Par\u00e1metros de Cotrol y Verificaci\u00f3n (CCV) #
# -------------------------------------------------- #
CtrlTipoParamRolUs=ROL_USUARIOS
CtrlTipoParamTipoResult=TIPO_RESULT
CtrlTipoParamEstGuia=EST_GUIAS

# ----------------------------------------------- #
# Estados de Gu\u00edas de Cotrol y Verificaci\u00f3n (CCV) #
# ----------------------------------------------- #
CtrlGuiaVigente=VIGENTE
CtrlGuiaCerrada=CERRADA
CtrlGuiaAnulada=ANULADA
CtrlGuiaIntervenida=INTERVENIDA
CtrlGuiaSuspendida=SUSPENDIDA

# ------------- #
# T\u00edtulos Menús #
# ------------- #
# Inicio
Inicio=Inicio
# Gesti\u00f3n
GuiasConf=Gu\u00edas a confirmar
GuiasAcred=Gu\u00edas acreditadas
# Administraci\u00f3n

# ------------------- #
# Tipos de par\u00e1metros #
# ------------------- #
RolUsuarios=ROL_USUARIOS
TipoItem=TIPO_ITEM

# ----------------- #
# Roles de Usuarios #
# ----------------- #
Administrador=ADMINISTRADOR
Transformador=TRANSFORMADOR
Acopiador=ACOPIADOR
